production:
  domain: "seatshare@linode.yearg.in"
  deploy_to: "/srv/www/seatsha.re/public_html"
  repository: "https://github.com/stephenyeargin/seatshare.git"
  branch: "master"
  post_deploy_script: "application/bin/run_migrations.sh"

staging:
  domain: "seatshare@linode.yearg.in"
  deploy_to: "/srv/www/staging.seatsha.re/public_html"
  repository: "https://github.com/stephenyeargin/seatshare.git"
  branch: "master"
  post_deploy_script: "application/bin/run_migrations.sh"